package se.yrgo.dataaccess;

import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import se.yrgo.domain.Call;
import se.yrgo.domain.Customer;
import se.yrgo.services.customers.CustomerNotFoundException;

import javax.xml.crypto.Data;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;

public class CustomerDaoJdbcTemplateImpl implements CustomerDao {
    private JdbcTemplate jdbcTemplate;

    // Create tables
    private static final String CREATE_CUSTOMER_TBL_SQL = "create table CUSTOMER(CUSTOMER_ID VARCHAR(20) PRIMARY KEY, COMPANY_NAME VARCHAR(50), EMAIL VARCHAR(30), TELEPHONE VARCHAR(20), NOTES VARCHAR(300))";
    private static final String CREATE_CALL_TBL_SQL = "create table CALL_TBL(CALL_ID integer generated by default as identity (start with 1, increment by 1) PRIMARY KEY, TIME_DATE TIMESTAMP, NOTES VARCHAR(300), CUSTOMER_ID VARCHAR(20), CONSTRAINT FK_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID))";

    // SQL queries
    private static final String INSERT_CUSTOMER_SQL = "insert into CUSTOMER(CUSTOMER_ID, COMPANY_NAME, EMAIL, TELEPHONE, NOTES) values (?, ?, ?, ?, ?)";
    private static final String GET_CUSTOMER_BY_ID_SQL = "select * from CUSTOMER where CUSTOMER_ID=?";
    private static final String GET_CUSTOMERS_BY_NAME_SQL = "select * from CUSTOMER where COMPANY_NAME=?";
    private static final String UPDATE_CUSTOMER_SQL = "UPDATE CUSTOMER SET COMPANY_NAME=?, EMAIL=?, TELEPHONE=?, NOTES=? WHERE CUSTOMER_ID=?";
    private static final String DELETE_CUSTOMER_SQL = "delete from CUSTOMER where CUSTOMER_ID=?";
    private static final String GET_ALL_CUSTOMERS_SQL = "select * from CUSTOMER";
    private static final String ADD_CALL_SQL = "insert into CALL_TBL(TIME_DATE, NOTES, CUSTOMER_ID) values (?, ?, ?)";
    private static final String GET_CALLS_BY_CUSTOMER_ID_SQL = "select* from CALL_TBL where CUSTOMER_ID=?";

    public CustomerDaoJdbcTemplateImpl(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    public void createTables() {
        try {
            this.jdbcTemplate.update(CREATE_CUSTOMER_TBL_SQL);
            this.jdbcTemplate.update(CREATE_CALL_TBL_SQL);
        } catch (org.springframework.jdbc.BadSqlGrammarException e) {
            System.out.println("Customer and/or Call tables may already exist");
        }
    }

    @Override
    public void create(Customer customer) {
        jdbcTemplate.update(INSERT_CUSTOMER_SQL, customer.getCustomerId(), customer.getCompanyName(), customer.getEmail(), customer.getTelephone(), customer.getNotes());
    }

    @Override
    public Customer getById(String customerId) throws RecordNotFoundException {
        try {
            return jdbcTemplate.queryForObject(GET_CUSTOMER_BY_ID_SQL, new CustomerMapper(), customerId);
        } catch (DataAccessException e) {
            throw new RecordNotFoundException();
        }
    }

    @Override
    public List<Customer> getByName(String name) throws RecordNotFoundException {
        try {
            return jdbcTemplate.query(GET_CUSTOMERS_BY_NAME_SQL, new CustomerMapper(), name);
        } catch (DataAccessException e) {
            throw new RecordNotFoundException();
        }
    }

    @Override
    public void update(Customer customerToUpdate) throws RecordNotFoundException {
        try {
            jdbcTemplate.update(UPDATE_CUSTOMER_SQL, customerToUpdate.getCompanyName(), customerToUpdate.getEmail(), customerToUpdate.getTelephone(), customerToUpdate.getNotes(), customerToUpdate.getCustomerId());
        } catch (DataAccessException e) {
            throw new RecordNotFoundException();
        }
    }

    @Override
    public void delete(Customer oldCustomer) throws RecordNotFoundException {
        try {
            jdbcTemplate.update(DELETE_CUSTOMER_SQL, oldCustomer.getCustomerId());
        } catch (DataAccessException e) {
            throw new RecordNotFoundException();
        }
    }

    @Override
    public List<Customer> getAllCustomers() {
        return jdbcTemplate.query(GET_ALL_CUSTOMERS_SQL, new CustomerMapper());
    }


    @Override
    public Customer getFullCustomerDetail(String customerId) throws RecordNotFoundException {
        try {
            Customer customer = jdbcTemplate.queryForObject(GET_CUSTOMER_BY_ID_SQL, new CustomerMapper(), customerId);
            List<Call> calls = jdbcTemplate.query(GET_CALLS_BY_CUSTOMER_ID_SQL, new CallMapper(), customerId);
            customer.setCalls(calls);
            return customer;
        } catch (DataAccessException e) {
            throw new RecordNotFoundException();
        }
    }

    @Override
    public void addCall(Call newCall, String customerId) throws RecordNotFoundException {
        try {
            jdbcTemplate.update(ADD_CALL_SQL, newCall.getTimeAndDate(), newCall.getNotes(), customerId);
        } catch (DataAccessException e) {
            throw new RecordNotFoundException();
        }
    }

    class CustomerMapper implements RowMapper<Customer> {
        @Override
        public Customer mapRow(ResultSet rs, int rowNumber) throws SQLException {
            String customerId = rs.getString("CUSTOMER_ID");
            String companyName = rs.getString("COMPANY_NAME");
            String email = rs.getString("EMAIL");
            String telephone = rs.getString("TELEPHONE");
            String notes = rs.getString("NOTES");
            Customer customer = new Customer(customerId, companyName, email, telephone, notes);
            return customer;
        }
    }

    class CallMapper implements RowMapper<Call> {
        @Override
        public Call mapRow(ResultSet rs, int rowNumber) throws SQLException {
            Date timedate = rs.getDate("TIME_DATE");
            String notes = rs.getString("NOTES");
            return new Call(notes, timedate);
        }
    }
}
